script: bash ./bin/deploy.sh
env:
  global:
  - GH_REF: github.com/clintonhalpin/hsfi-scripted.git
language: node_js
node_js:
- '4.0'
cache: 
  directories:
    - node_modules
branches:
  only:
    - master
